"""
Auto-generate weekly portfolio intelligence digest.
Scrapes fresh data, analyzes all portfolios, generates markdown report.

Run every Monday via cron or manually: python -m cse.weekly_digest
"""
import json
import sqlite3
import numpy as np
from datetime import datetime
from pathlib import Path
from collections import Counter

from cse.glider_api import scrape_all
from cse.resolve_tokens import main as resolve_main

DATA_DIR = Path(__file__).parent.parent / "data"
REPORTS_DIR = Path(__file__).parent.parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)
DB_PATH = DATA_DIR / "portfolios.db"

def generate():
    # fresh scrape
    print("Scraping latest portfolio data...")
    scrape_all()
    print("Resolving tokens...")
    resolve_main()

    conn = sqlite3.connect(DB_PATH)

    portfolios = conn.execute("""
        SELECT p.strategy_id, p.discord_user, p.blueprint_name, p.num_assets
        FROM portfolios p ORDER BY p.num_assets DESC
    """).fetchall()

    allocs = conn.execute("""
        SELECT strategy_id, symbol, weight_pct FROM allocations
    """).fetchall()

    alloc_map = {}
    for sid, sym, w in allocs:
        alloc_map.setdefault(sid, []).append((sym, w))

    # token popularity
    all_tokens = []
    for sid, items in alloc_map.items():
        for sym, w in items:
            all_tokens.append(sym)

    token_freq = Counter(all_tokens)
    n_portfolios = len(portfolios)

    # strategy types
    type_counts = Counter()
    risk_scores = []
    for sid, user, name, n_assets in portfolios:
        items = alloc_map.get(sid, [])
        syms = [s for s, w in items]
        wts = [w for s, w in items]
        if not wts:
            continue
        w_arr = np.array(wts) / sum(wts)
        hhi = float(np.sum(w_arr ** 2))

        if set(syms) <= {"USDC", "USDT", "DAI"}:
            t = "stablecoin"
        elif len(syms) == 1:
            t = "single-asset"
        elif len(syms) >= 5:
            t = "diversified"
        else:
            t = "balanced"
        type_counts[t] += 1

        score = max(0, min(100, round((1 - hhi) * 40 + min(30, len(syms) * 5) + 15)))
        risk_scores.append((sid, user, score, syms, wts))

    risk_scores.sort(key=lambda x: x[2], reverse=True)

    date = datetime.now().strftime("%Y-%m-%d")
    week = datetime.now().strftime("%B %d, %Y")

    md = [
        f"# Glider Community Portfolio Intelligence",
        f"**Week of {week}** | {n_portfolios} portfolios tracked\n",
        "---\n",
        "## Asset Popularity\n",
        "| Token | In Portfolios | Share |",
        "|-------|--------------|-------|",
    ]
    for tok, cnt in token_freq.most_common(10):
        md.append(f"| {tok} | {cnt} | {cnt/n_portfolios*100:.0f}% |")

    md.extend([
        "\n## Strategy Distribution\n",
        "| Type | Count | % |",
        "|------|-------|---|",
    ])
    for t, cnt in type_counts.most_common():
        md.append(f"| {t} | {cnt} | {cnt/n_portfolios*100:.0f}% |")

    md.extend([
        "\n## Portfolio Leaderboard (by diversification score)\n",
        "| Rank | User | Score | Assets |",
        "|------|------|-------|--------|",
    ])
    for i, (sid, user, score, syms, wts) in enumerate(risk_scores[:10]):
        asset_str = ", ".join(f"{s}({w:.0f}%)" for s, w in zip(syms, wts))[:50]
        md.append(f"| {i+1} | {user} | {score}/100 | {asset_str} |")

    avg_score = np.mean([s[2] for s in risk_scores]) if risk_scores else 0
    md.extend([
        f"\n## Community Health\n",
        f"- **Average score**: {avg_score:.0f}/100",
        f"- **Portfolios tracked**: {n_portfolios}",
        f"- **Unique tokens**: {len(token_freq)}",
        f"- **Most popular**: {token_freq.most_common(1)[0][0]} ({token_freq.most_common(1)[0][1]} portfolios)",
        f"- **Single-asset portfolios**: {type_counts.get('single-asset', 0)} ({type_counts.get('single-asset', 0)/n_portfolios*100:.0f}%)",
        f"\n## Key Insights\n",
    ])

    # auto-generate insights
    if type_counts.get("single-asset", 0) > n_portfolios * 0.25:
        md.append(f"- **High single-asset concentration**: {type_counts['single-asset']} users ({type_counts['single-asset']/n_portfolios*100:.0f}%) have 100% in one token. Education opportunity.")

    top_token = token_freq.most_common(1)[0]
    if top_token[1] > n_portfolios * 0.4:
        md.append(f"- **Herd behavior**: {top_token[0]} is in {top_token[1]}/{n_portfolios} portfolios. Community is correlated — a {top_token[0]} drawdown hits everyone.")

    identical = [s for s in risk_scores if len(s[3]) == 6 and "BRETT" in s[3] and "DEGEN" in s[3]]
    if len(identical) > 2:
        md.append(f"- **Template copying**: {len(identical)} users running identical 6-asset Base template. Low strategy diversity.")

    md.extend([
        f"\n---",
        f"*Auto-generated by Community Signal Engine | Portfolio Arena by Jay Dasondee*",
    ])

    report = "\n".join(md)
    path = REPORTS_DIR / f"weekly_{date}.md"
    path.write_text(report, encoding="utf-8")
    print(f"\nReport: {path}")

    latest = REPORTS_DIR / "latest.md"
    latest.write_text(report, encoding="utf-8")

    conn.close()
    return report

if __name__ == "__main__":
    generate()
